### ISSUE TITLE
Missing outputs in DB when creating multiple jobs

### ISSUE THREAD

**Issue by yoannisj** [yoannisj/craft-coconut#1]
When creating multiple jobs in one single request, only the last jobs' outputs seem to be saved in the database.

This means that only the last job's notifications succeed. All other jobs have failed notifications because the outputs can't be found in the DB. Worse, they will be re-created even if their output files have been transcoded and uploaded.

**Comment by denisyilmaz** [comment]
I've checked the coconut panel and saw that i can resend the `output.complete` event which fails currently on these jobs.
In the error logs of the server this message is printed on this failed job:
```
2021-11-30 08:28:56 [-][-][-][error][application] NOTIFY [#8i5PqJ3Od74hY1] output.completed
2021-11-30 08:28:56 [-][-][-][error][yii\base\InvalidArgumentException] yii\base\InvalidArgumentException: Can not add output to a Job that has already been ran. in /home/runcloud/webapps/stiniroehrs-web-staging/vendor/yoannisj/craft-coconut/src/models/Job.php:963
Stack trace:
#0 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/yoannisj/craft-coconut/src/helpers/JobHelper.php(1011): yoannisj\coconut\models\Job->addOutput()
#1 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/yoannisj/craft-coconut/src/services/Jobs.php(418): yoannisj\coconut\helpers\JobHelper::populateJobFromData()
#2 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/yoannisj/craft-coconut/src/controllers/JobsController.php(108): yoannisj\coconut\services\Jobs->updateJobOutput()
#3 [internal function]: yoannisj\coconut\controllers\JobsController->actionNotify()
#4 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#5 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#6 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#7 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#8 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/craftcms/cms/src/web/Application.php(278): yii\base\Module->runAction()
#9 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/craftcms/cms/src/web/Application.php(581): craft\web\Application->runAction()
#10 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest()
#11 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#12 /home/runcloud/webapps/stiniroehrs-web-staging/web/index.php(25): yii\base\Application->run()
```

**Comment by denisyilmaz** [comment]
so it seems the `coconutId` must be somehow in the database. otherwise this line wouldnt fail i guess:
[[                'Can not add output to a Job that has already been ran.');](https://github.com/yoannisj/craft-coconut/blob/4824c4129f48ad048becf85e8ddc2c436d4e3a97/src/models/Job.php#L964)](https://github.com/yoannisj/craft-coconut/blob/4824c4129f48ad048becf85e8ddc2c436d4e3a97/src/models/Job.php#L959-L965)

**Comment by denisyilmaz** [comment]
now i triggerd a new array of jobs being sent to coconut (which only the first one completes). This is the error all other jobs get:
```
2021-11-30 08:34:30 [-][-][-][error][application] OUTPUT ERRORS
2021-11-30 08:34:30 [-][-][-][error][yii\web\HttpException:500] yii\web\ServerErrorHttpException: Could not handle job notification in /home/runcloud/webapps/stiniroehrs-web-staging/vendor/yoannisj/craft-coconut/src/controllers/JobsController.php:129
Stack trace:
#0 [internal function]: yoannisj\coconut\controllers\JobsController->actionNotify()
#1 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#2 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#3 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#4 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#5 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/craftcms/cms/src/web/Application.php(278): yii\base\Module->runAction()
#6 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/craftcms/cms/src/web/Application.php(581): craft\web\Application->runAction()
#7 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest()
#8 /home/runcloud/webapps/stiniroehrs-web-staging/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#9 /home/runcloud/webapps/stiniroehrs-web-staging/web/index.php(25): yii\base\Application->run()
```

additionally, before the output error all failed jobs have the following message:
```
2021-11-30 08:34:30 [-][-][-][error][application] NOTIFY [#DNR7Tqxi0yjWM2] input.transferred
2021-11-30 08:34:30 [-][-][-][error][application] JOB ERRORS
2021-11-30 08:34:30 [-][-][-][error][application] [
    'Outputs cannot be blank.',
]
```
